#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <simplecrc/reference.h>
#include <simplecrc.h>

#include "utility/algo_test_utils.h"

/* Generated by crcany */
uint32_t crc24lte_a_bit(uint32_t crc, void const *mem, size_t len)
{
	unsigned char const *data = mem;
	if (data == NULL)
		return 0;
	for (size_t i = 0; i < len; i++) {
		crc ^= (uint32_t)data[i] << 16;
		for (unsigned k = 0; k < 8; k++) {
			crc = crc & 0x800000 ? (crc << 1) ^ 0x864cfb : crc << 1;
		}
	}
	crc &= 0xffffff;
	return crc;
}

EXHAUSTIVE_CRC_CHECK(CRC_LTE_A, crc24lte_a_bit)
