#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <simplecrc/reference.h>
#include <simplecrc.h>

#include "utility/algo_test_utils.h"

/* Generated by crcany */
uint32_t crc32autosar_bit(uint32_t crc, void const *mem, size_t len)
{
	unsigned char const *data = mem;
	if (data == NULL)
		return 0;
	crc = ~crc;
	for (size_t i = 0; i < len; i++) {
		crc ^= data[i];
		for (unsigned k = 0; k < 8; k++) {
			crc = crc & 1 ? (crc >> 1) ^ 0xc8df352f : crc >> 1;
		}
	}
	crc = ~crc;
	return crc;
}

EXHAUSTIVE_CRC_CHECK(CRC_AUTOSAR_32, crc32autosar_bit)
