#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <simplecrc/reference.h>
#include <simplecrc.h>

#include "utility/algo_test_utils.h"

/* Generated by crcany */
uint16_t crc16ibm_3740_bit(uint16_t crc, void const *mem, size_t len)
{
	unsigned char const *data = mem;
	if (data == NULL)
		return 0xffff;
	for (size_t i = 0; i < len; i++) {
		crc ^= (uint16_t)data[i] << 8;
		for (unsigned k = 0; k < 8; k++) {
			crc = crc & 0x8000 ? (crc << 1) ^ 0x1021 : crc << 1;
		}
	}
	return crc;
}

int main(int argc, char **argv)
{
	int test_status = EXIT_FAILURE;
	const size_t buf_size = 256;
	uintmax_t expected = 0;
	uintmax_t computed = 0;

	unsigned char *buffer = calloc(buf_size, 1);
	if (!buffer) {
		return test_status;
	}

	// Ensure test buffer checks all values in lookup table
	fill_test_array(&buffer, buf_size);

	expected = CRCANY_INVOKE_ALGO(crc16ibm_3740_bit, 16, buffer, buf_size);
	computed = compute_crc(CRC_IBM_3740, buffer, buf_size);

	if (expected == computed) {
		printf("Test succeeded\n");
		test_status = EXIT_SUCCESS;
	} else {
		fprintf(stderr, "Test failed\nexpected: 0x%lx\ncomputed: 0x%lx\n",
				expected, computed);
		test_status = EXIT_FAILURE;
	}

	free(buffer);
	return test_status;
}
