#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <simplecrc/reference.h>
#include <simplecrc.h>

#include "utility/algo_test_utils.h"

/* Generated by crcany */
uint16_t crc12dect_bit(uint16_t crc, void const *mem, size_t len)
{
	unsigned char const *data = mem;
	if (data == NULL)
		return 0;
	for (size_t i = 0; i < len; i++) {
		crc ^= (uint16_t)data[i] << 4;
		for (unsigned k = 0; k < 8; k++) {
			crc = crc & 0x800 ? (crc << 1) ^ 0x80f : crc << 1;
		}
	}
	crc &= 0xfff;
	return crc;
}

EXHAUSTIVE_CRC_CHECK(CRC_DECT_12, crc12dect_bit)
