#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <simplecrc/reference.h>
#include <simplecrc.h>

#include "utility/algo_test_utils.h"

/* Generated by crcany */
uint8_t crc8cdma2000_bit(uint8_t crc, void const *mem, size_t len)
{
	unsigned char const *data = mem;
	if (data == NULL)
		return 0xff;
	for (size_t i = 0; i < len; i++) {
		crc ^= data[i];
		for (unsigned k = 0; k < 8; k++) {
			crc = crc & 0x80 ? (crc << 1) ^ 0x9b : crc << 1;
		}
	}
	return crc;
}

EXHAUSTIVE_CRC_CHECK(CRC_CDMA2000_8, crc8cdma2000_bit)
