#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

#include <simplecrc/reference.h>
#include <simplecrc.h>

#include "utility/algo_test_utils.h"

/* Generated by crcany */
uint64_t crc40gsm_bit(uint64_t crc, void const *mem, size_t len)
{
	unsigned char const *data = mem;
	if (data == NULL)
		return 0xffffffffff;
	crc = ~crc;
	for (size_t i = 0; i < len; i++) {
		crc ^= (uint64_t)data[i] << 32;
		for (unsigned k = 0; k < 8; k++) {
			crc = crc & 0x8000000000 ? (crc << 1) ^ 0x4820009 : crc << 1;
		}
	}
	crc = ~crc;
	crc &= 0xffffffffff;
	return crc;
}

int main(int argc, char **argv)
{
	int test_status = EXIT_FAILURE;
	const size_t buf_size = 256;
	uintmax_t expected = 0;
	uintmax_t computed = 0;

	char *buffer = calloc(buf_size, 1);
	if (!buffer) {
		return test_status;
	}

	// Ensure test buffer checks all values in lookup table
	fill_test_array(&buffer, buf_size);

	expected = CRCANY_INVOKE_ALGO(crc40gsm_bit, 40, buffer, buf_size);
	computed = compute_crc(CRC_GSM_40, buffer, buf_size);

	if (expected == computed) {
		printf("Test succeeded\n");
		test_status = EXIT_SUCCESS;
	} else {
		fprintf(stderr, "Test failed\nexpected: 0x%lx\ncomputed: 0x%lx\n",
				expected, computed);
		test_status = EXIT_FAILURE;
	}

	free(buffer);
	return test_status;
}
